spring:
  datasource:
    hikari:
      jdbc-url: ${commerce.spring.datasource.url}
      username: ${commerce.spring.datasource.username}
      password: ${commerce.spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

decorator:
  datasource:
    p6spy:
      enable-logging: on

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
    tags-sorter: alpha
