spring:
  datasource:
    hikari:
      jdbc-url: ${commerce.spring.datasource.url}
      username: ${commerce.spring.datasource.username}
      password: ${commerce.spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            redirect-uri: ${kakao.redirect.uri}
            grant-type: ${kakao.grant.type}
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            redirect-uri: ${google.redirect.uri}
            grant-type: ${google.grant.type}
#            scope: profile,email





decorator:
  datasource:
    p6spy:
      enable-logging: on

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

